language: php

git:
  quiet: true

php:
  - 7.2
  - 7.3
  - 7.4

before_install:
  - sudo apt-get install hunspell
  - travis_retry composer self-update

install:
  - travis_retry composer update

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit tests/

after_script:
  - php vendor/bin/php-coveralls -v